services:
  collector:
    image: samcrosoft/csp-notifier-golang:v1
    ports:
      - "3000:3000"
    working_dir: /app
    tty: true
    networks:
      - app
    environment:
      - DB_DSN=root:example@tcp(db:3306)/csp_reports
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_DATABASE=csp_reports
      - MARIADB_ROOT_PASSWORD=example
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db
networks:
  app: